In [35]:
import sys
sys.path.insert(0, '../../')

In [36]:
import warnings
warnings.filterwarnings('ignore')

import sys
import os
import math
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, KFold
from sklearn.metrics import r2_score
from sklearn.base import clone
from tqdm import tqdm
from pickle import load
from scipy.stats import ttest_ind

# load local variables
from src.config import *
from src.load_models import select_model
from src.utils import calculate_r2_score, calculate_per_diff
from src.utils import calculate_y_LOD, find_score
from src.feature_selection import ModelSelection
from src.graph_visualization import feature_selection_tabularize, plot_model_vs_score, visualization_class_stratified
from src.outlier_detection import find_outliers_remove
from src.utils import evaluate_score_class_stratified

from sklearn.ensemble  import RandomForestClassifier

from sklearn.preprocessing import StandardScaler
# from sklearn.gaussian_process.kernels import Matern, RBF

In [37]:
def ValidationPerformanceWithStratified(X:pd.DataFrame,
                                        y:pd.Series,
                                        models:list,
                                        save_dir:str,
                                        kf:KFold,
                                        features_list:dict, 
                                        param_list:dict,
                                        y_LOD:float = 1.0163597575709407,
                                        use_classifier:bool=False,
                                        remove_zero:bool=False) -> None:

    
    
    for model_name in models:
        model = select_model(model_name)
            
        selected_feature_set = features_list[model_name]

        # Set the model parameters extrinsic
        model.set_params(**param_list[model_name])
    

        y_pred_all, y_true_all = [], []
        y_pred_prime_all, y_true_prime_all = [], []
        fold_test_per_error_all, fold_test_rsquare_all = [], []
        
        # Calculate score for each folds
        for train_index, test_index in kf.split(X):
            model_ = clone(model)

            # Split the data into training and testing sets
            X_train  = X.iloc[train_index]
            y_train  = y.iloc[train_index]
            
            X_test   = X.iloc[test_index]
            y_test   = y.iloc[test_index]

            # Train model with a fraction of folds only on selected features
            model_.fit(X_train[selected_feature_set], y_train)               

            
            y_pred       = model_.predict(X_test[selected_feature_set])       # prediction on remaining folds
            # y_pred_prime = model_.predict(X_test_prime[selected_feature_set]) # prediction on testing data with zero concentration removed
           
            
            # # Calculate metrics with model trained on folds
            # fold_test_per_error_all.append(calculate_per_diff(y_test_prime, y_pred_prime, y_LOD)) # Zero index data should be removed
            # fold_test_rsquare_all.append(calculate_r2_score(y_test_prime, y_pred_prime))

            y_pred_all.append(y_pred)
            y_true_all.append(y_test)

        y_pred_all = np.concatenate(y_pred_all, axis=0) 
        y_true_all = np.concatenate(y_true_all, axis=0) 

        
        # Remove zero concentration calculating
        if  remove_zero:
            y_pred_all      = pd.Series(y_pred_all)
            y_true_all      = pd.Series(y_true_all)
            
            indx_gt_zero    = list(y_true_all[y_true_all!=0].index)
            y_pred_all      = y_pred_all.loc[indx_gt_zero].to_numpy()
            y_true_all      = y_true_all.loc[indx_gt_zero].to_numpy()


        model_.fit(X[selected_feature_set], y)

        # Calculate for testing dataset
        y_pred_prime       = model_.predict(X_test_prime[selected_feature_set])
        test_rsquare_all   = calculate_r2_score(y_test_prime, y_pred_prime)
        test_per_error_all = calculate_per_diff(y_test_prime, y_pred_prime, y_LOD)

        # Calculate for all folds
        r2_score_train_folds  = calculate_r2_score(y_true_all, y_pred_all)
        per_error_train_folds = calculate_per_diff(y_true_all, y_pred_all, y_LOD)

        
        return (r2_score_train_folds, per_error_train_folds), (np.mean(test_rsquare_all), np.mean(test_per_error_all))

In [38]:
features_list= {'KNN':    ['min(dS/dV)', 'max(S)'], 
                'Linear': ['min(dS/dV)', 'V_max(S)', 'f2', 'f1', 'V_max(dS/dV)'], 
                'RF':     ['min(dS/dV)', 'area(S)', 'f2', 'V_max(dS/dV)'],
                'SVM':    ['min(dS/dV)', 'area(S)', 'vcenter', 'V_max(dS/dV)', 'max(dS/dV)'], 
                'GP':     ['min(dS/dV)', 'area(S)', 'V_max(dS/dV)', 'max(dS/dV)']}

param_list =  {'KNN': {'n_neighbors': 12, 'weights': 'distance', 'metric': 'manhattan'},
               'Linear': {},
               'RF': {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 2},
               'SVM': {'C': 250, 'gamma': 0.1, 'kernel': 'rbf'},
               'GP': {'kernel': 1**2 * Matern(length_scale=1, nu=1.5), 'alpha': 2.5}}

In [39]:
y_LOD = 1.0163597575709407

dataset_name = 'ML6'
remove_zero  = True
dataset_root = '../../dataset'

# Load Extracted features dataset
ML6_1 = pd.read_excel(f'{dataset_root}/ML6/Day 1 Data/feature_extraction_noise_None.xlsx')
ML6_2 = pd.read_excel(f'{dataset_root}/ML6/Day 2 Data/feature_extraction_noise_None.xlsx')

ML6_1['dataset_name'] = '1'
ML6_2['dataset_name'] = '2'
final_dataset = pd.concat([ML6_1, ML6_2], ignore_index=True)
final_dataset = pd.concat([ML6_1, ML6_2], ignore_index=True)
final_dataset['label'] = final_dataset['file'].apply(lambda x: x.split('/')[-1].split('_')[-2].replace('cbz','')).apply(lambda x: int(x))

final_dataset.rename(columns={"PH": 'max(S)', 'signal_std':'std(S)', 'signal_mean':'mean(S)', 'peak area':'area(S)', \
                        'dS_dV_area':'area(dS/dV)', 'dS_dV_max_peak':'max(dS/dV)', 'dS_dV_min_peak':'min(dS/dV)',\
                    'dS_dV_peak_diff':'max(dS/dV) - min(dS/dV)', \
                    'peak V':'V_max(S)', 'dS_dV_max_V':'V_max(dS/dV)', 'dS_dV_min_V':'V_min(dS/dV)',\
        }, inplace = True)

final_dataset = final_dataset[['area(S)', 'max(S)', 'max(dS/dV)', 'min(dS/dV)', 'V_max(S)', 'vcenter', 'V_max(dS/dV)', 'V_min(dS/dV)', 'f1', 'f2', 'file', 'label']]

max_seed      = 200
num_seed      = 100

# Assign the probability
p             = np.array([0.2]*max_seed)
p[41]         = 1.0         # 42 should be in the random state
p             = p / p.sum() # normalize the probability

random_states = np.random.choice(max_seed, size=num_seed, p=p)

# for i in range(20):
compare_test_train_r2_df         = pd.DataFrame(columns=['random_seed', 'val_score', 'test_score'])
compare_test_train_per_diff_df   = pd.DataFrame(columns=['random_seed', 'val_score', 'test_score'])

for random_state in range(1000):
    # Remove outliers from training dataset
    train, test           = train_test_split(final_dataset, test_size=0.4, shuffle=True, random_state=random_state, stratify=final_dataset['label'])
    X_filtered, outlier_S = find_outliers_remove('max(S)',  train, save_path='')
    X_filtered, outlier_S = find_outliers_remove('V_max(S)',  X_filtered, save_path='')
    
    X_train = X_filtered.drop(['label', 'file'], axis=1)
    y_train = X_filtered['label']
    X_test_prime  = test.drop(['label', 'file'], axis=1)
    y_test_prime  = test['label']
    
    if remove_zero:
        indx_gt_zero    = list(y_test_prime[y_test_prime!=0].index)
        X_test_prime         = X_test_prime.loc[indx_gt_zero]
        y_test_prime         = y_test_prime.loc[indx_gt_zero]
        
    
    models      = ['Linear']
    root_dir    = f'../../results/Journal_paper/{dataset_name}_zero_removal'
    weight_path = '../../weights/Journal_paper'
    
    kf        = KFold(n_splits=5, shuffle=True, random_state=42) 
    
    (train_fold_r2, train_fold_per_error), (test_fold_r2, test_fold_per_err) = ValidationPerformanceWithStratified(X_train, 
                                        y_train, 
                                        models, 
                                        root_dir, 
                                        kf=kf, 
                                        features_list=features_list, 
                                        param_list= param_list, 
                                        y_LOD=y_LOD,
                                        remove_zero=remove_zero,
                                        use_classifier=False)

    temp_r2     = pd.DataFrame({'random_seed':[random_state], 'val_score':[train_fold_r2], 'test_score':[test_fold_r2]})
    perError_r2 = pd.DataFrame({'random_seed':[random_state], 'val_score':[train_fold_per_error], 'test_score':[test_fold_per_err]})
    
    compare_test_train_r2_df       = pd.concat([compare_test_train_r2_df, temp_r2])
    compare_test_train_per_diff_df = pd.concat([compare_test_train_per_diff_df, perError_r2])

In [40]:
compare_test_train_r2_df['val_score'].mean(), compare_test_train_r2_df['test_score'].mean()

(0.7758281596173429, 0.7836786078089234)

In [41]:
compare_test_train_r2_df['diff_mean_val_score']  = compare_test_train_r2_df['val_score'].apply(lambda x: abs(x - 0.775))
compare_test_train_r2_df['diff_mean_test_score'] = compare_test_train_r2_df['test_score'].apply(lambda x: abs(x - 0.7836))
compare_test_train_r2_df['avg_diff_mean_score']  = compare_test_train_r2_df.apply(lambda x: ( x['diff_mean_val_score'] + x['diff_mean_test_score'])/2, axis=1)
sorted_output_r2  = compare_test_train_r2_df.sort_values(by=['avg_diff_mean_score'])
sorted_output_r2.head(50)

,random_seed,val_score,test_score,diff_mean_val_score,diff_mean_test_score,avg_diff_mean_score
0,622,0.774430,0.783767,0.000570,0.000167,0.000368
0,295,0.774465,0.783257,0.000535,0.000343,0.000439
0,693,0.774678,0.784233,0.000322,0.000633,0.000478
0,617,0.775615,0.784032,0.000615,0.000432,0.000523
0,941,0.775393,0.784749,0.000393,0.001149,0.000771
0,912,0.773730,0.784114,0.001270,0.000514,0.000892
0,28,0.773873,0.782739,0.001127,0.000861,0.000994
0,316,0.776854,0.783393,0.001854,0.000207,0.001031
0,75,0.775074,0.781495,0.000074,0.002105,0.001090
0,523,0.776821,0.783963,0.001821,0.000363,0.001092
0,559,0.776967,0.783851,0.001967,0.000251,0.001109
0,873,0.776423,0.782244,0.001423,0.001356,0.001390
0,76,0.776420,0.782127,0.001420,0.001473,0.001447
0,880,0.774911,0.780440,0.000089,0.003160,0.001625
0,611,0.772310,0.784247,0.002690,0.000647,0.001669
0,378,0.776848,0.782037,0.001848,0.001563,0.001706
0,283,0.773669,0.785975,0.001331,0.002375,0.001853
0,782,0.775164,0.779737,0.000164,0.003863,0.002013
0,660,0.779135,0.783347,0.004135,0.000253,0.002194
0,470,0.773615,0.786615,0.001385,0.003015,0.002200
0,908,0.778037,0.782103,0.003037,0.001497,0.002267
0,315,0.773150,0.780884,0.001850,0.002716,0.002283
0,77,0.771667,0.785127,0.003333,0.001527,0.002430
0,145,0.773170,0.780464,0.001830,0.003136,0.002483
0,268,0.770049,0.783660,0.004951,0.000060,0.002505
0,918,0.772607,0.780689,0.002393,0.002911,0.002652
0,512,0.770788,0.782338,0.004212,0.001262,0.002737
0,131,0.776489,0.787872,0.001489,0.004272,0.002881
0,662,0.772254,0.786616,0.002746,0.003016,0.002881
0,280,0.775231,0.778061,0.000231,0.005539,0.002885
0,386,0.779869,0.782618,0.004869,0.000982,0.002926
0,866,0.779512,0.785083,0.004512,0.001483,0.002997
0,58,0.771632,0.786597,0.003368,0.002997,0.003183
0,943,0.774645,0.777583,0.000355,0.006017,0.003186
0,849,0.775189,0.777329,0.000189,0.006271,0.003230
0,981,0.778695,0.780722,0.003695,0.002878,0.003286
0,83,0.774825,0.790006,0.000175,0.006406,0.003291
0,276,0.774094,0.789359,0.000906,0.005759,0.003333
0,588,0.770421,0.785730,0.004579,0.002130,0.003354
0,521,0.781309,0.784194,0.006309,0.000594,0.003452
0,909,0.773275,0.788833,0.001725,0.005233,0.003479
0,138,0.775938,0.789916,0.000938,0.006316,0.003627
0,8,0.775238,0.790632,0.000238,0.007032,0.003635
0,846,0.770011,0.785930,0.004989,0.002330,0.003660
0,771,0.774467,0.790438,0.000533,0.006838,0.003686
0,454,0.775158,0.790848,0.000158,0.007248,0.003703
0,532,0.771584,0.787602,0.003416,0.004002,0.003709
0,921,0.782070,0.783954,0.007070,0.000354,0.003712
0,601,0.782059,0.783159,0.007059,0.000441,0.003750
0,164,0.778087,0.779153,0.003087,0.004447,0.003767

In [8]:
compare_test_train_r2_df['difference'] = compare_test_train_r2_df.apply(lambda x: x['val_score'] - x['test_score'], axis=1)
train_winner = len(compare_test_train_r2_df[compare_test_train_r2_df['difference'] > 0])
total        = len(compare_test_train_r2_df)

print(train_winner/total*100)

42.9

In [9]:
compare_test_train_per_diff_df['difference'] = compare_test_train_per_diff_df.apply(lambda x: x['val_score'] - x['test_score'], axis=1)
train_winner = len(compare_test_train_per_diff_df[compare_test_train_per_diff_df['difference'] < 0])
total        = len(compare_test_train_per_diff_df)

print(train_winner/total*100)

68.2

In [10]:
compare_test_train_per_diff_df['val_score'].mean(), compare_test_train_per_diff_df['test_score'].mean()

(18.493406425781348, 19.457083815865147)

In [28]:
compare_test_train_per_diff_df['diff_mean_val_score']  = compare_test_train_per_diff_df['val_score'].apply(lambda x: abs(x - 18.49))
compare_test_train_per_diff_df['diff_mean_test_score'] = compare_test_train_per_diff_df['test_score'].apply(lambda x: abs(x - 19.45))
compare_test_train_per_diff_df['avg_diff_mean_score']  = compare_test_train_per_diff_df.apply(lambda x: ( x['diff_mean_val_score'] + x['diff_mean_test_score'])/2, axis=1)
sorted_output_per  = compare_test_train_per_diff_df.sort_values(by=['avg_diff_mean_score'])
sorted_output_per.head(50)

,random_seed,val_score,test_score,difference,diff_mean_val_score,diff_mean_test_score,avg_diff_mean_score),avg_diff_mean_score
0,579,18.510920,19.442827,-0.931906,0.020920,0.007173,0.014047,0.014047
0,559,18.444827,19.409898,-0.965072,0.045173,0.040102,0.042637,0.042637
0,122,18.587959,19.445349,-0.857390,0.097959,0.004651,0.051305,0.051305
0,963,18.409550,19.424606,-1.015056,0.080450,0.025394,0.052922,0.052922
0,330,18.517731,19.295927,-0.778196,0.027731,0.154073,0.090902,0.090902
0,651,18.520234,19.609068,-1.088834,0.030234,0.159068,0.094651,0.094651
0,564,18.411349,19.563530,-1.152181,0.078651,0.113530,0.096091,0.096091
0,526,18.456975,19.631642,-1.174667,0.033025,0.181642,0.107333,0.107333
0,157,18.280636,19.457843,-1.177207,0.209364,0.007843,0.108603,0.108603
0,431,18.411936,19.596671,-1.184736,0.078064,0.146671,0.112368,0.112368
0,947,18.511171,19.236712,-0.725541,0.021171,0.213288,0.117230,0.117230
0,329,18.625807,19.559428,-0.933621,0.135807,0.109428,0.122617,0.122617
0,563,18.274833,19.410206,-1.135374,0.215167,0.039794,0.127481,0.127481
0,50,18.614463,19.601373,-0.986910,0.124463,0.151373,0.137918,0.137918
0,696,18.504027,19.712619,-1.208592,0.014027,0.262619,0.138323,0.138323
0,429,18.604686,19.270974,-0.666289,0.114686,0.179026,0.146856,0.146856
0,503,18.441105,19.200966,-0.759862,0.048895,0.249034,0.148964,0.148964
0,363,18.563599,19.223441,-0.659842,0.073599,0.226559,0.150079,0.150079
0,637,18.454053,19.181317,-0.727264,0.035947,0.268683,0.152315,0.152315
0,893,18.382703,19.652010,-1.269307,0.107297,0.202010,0.154653,0.154653
0,85,18.476989,19.747824,-1.270834,0.013011,0.297824,0.155417,0.155417
0,935,18.389949,19.662817,-1.272868,0.100051,0.212817,0.156434,0.156434
0,191,18.527221,19.172986,-0.645766,0.037221,0.277014,0.157117,0.157117
0,777,18.294334,19.324952,-1.030618,0.195666,0.125048,0.160357,0.160357
0,931,18.440556,19.172201,-0.731645,0.049444,0.277799,0.163622,0.163622
0,750,18.783310,19.491303,-0.707993,0.293310,0.041303,0.167306,0.167306
0,788,18.196472,19.491905,-1.295432,0.293528,0.041905,0.167716,0.167716
0,485,18.651063,19.270899,-0.619836,0.161063,0.179101,0.170082,0.170082
0,55,18.720436,19.559788,-0.839352,0.230436,0.109788,0.170112,0.170112
0,721,18.511379,19.125571,-0.614192,0.021379,0.324429,0.172904,0.172904
0,858,18.527892,19.136860,-0.608968,0.037892,0.313140,0.175516,0.175516
0,640,18.210698,19.377586,-1.166887,0.279302,0.072414,0.175858,0.175858
0,859,18.721279,19.328766,-0.607487,0.231279,0.121234,0.176257,0.176257
0,568,18.392103,19.714479,-1.322376,0.097897,0.264479,0.181188,0.181188
0,334,18.325287,19.252188,-0.926902,0.164713,0.197812,0.181263,0.181263
0,204,18.452235,19.120676,-0.668441,0.037765,0.329324,0.183544,0.183544
0,405,18.624144,19.685455,-1.061311,0.134144,0.235455,0.184800,0.184800
0,128,18.661832,19.649773,-0.987941,0.171832,0.199773,0.185802,0.185802
0,420,18.858560,19.442219,-0.583659,0.368560,0.007781,0.188170,0.188170
0,304,18.186752,19.525205,-1.338453,0.303248,0.075205,0.189226,0.189226
0,641,18.129272,19.475683,-1.346412,0.360728,0.025683,0.193206,0.193206
0,21,18.580418,19.750968,-1.170550,0.090418,0.300968,0.195693,0.195693
0,542,18.539996,19.103592,-0.563596,0.049996,0.346408,0.198202,0.198202
0,724,18.356039,19.712869,-1.356830,0.133961,0.262869,0.198415,0.198415
0,866,18.453485,19.825930,-1.372445,0.036515,0.375930,0.206223,0.206223
0,720,18.204741,19.596197,-1.391456,0.285259,0.146197,0.215728,0.215728
0,421,18.737358,19.259762,-0.522404,0.247358,0.190238,0.218798,0.218798
0,789,18.441057,19.838829,-1.397772,0.048943,0.388829,0.218886,0.218886
0,573,18.103797,19.392159,-1.288362,0.386203,0.057841,0.222022,0.222022
0,80,18.509660,18.997713,-0.488052,0.019660,0.452287,0.235974,0.235974

In [34]:
sorted_output_per[sorted_output_per['random_seed']==622]
sorted_output_r2[sorted_output_r2['random_seed']==579]

,random_seed,val_score,test_score,difference,diff_mean_val_score,diff_mean_test_score,avg_diff_mean_score
0,579,0.78013,0.770708,0.009421,0.00513,0.012892,0.009011

# Paired T-test

In [43]:
from scipy.stats import ttest_rel

# Percent Error
# Null hypothesis is both the score are the same
# Alternative per_score_train < per_score_test = 'less'
t_stat, p_value = ttest_rel(compare_test_train_per_diff_df['test_score'].tolist(),
                            compare_test_train_per_diff_df['val_score'].tolist(),
                            alternative='less')

print(p_value)

1.0

In [44]:
# R2 Score
# Null hypothesis is both the score are the same
# Alternative r2_train > r2_test = 'greater'
t_stat, p_value = ttest_rel(compare_test_train_r2_df['test_score'].tolist(),
                            compare_test_train_r2_df['val_score'].tolist(),
                            alternative='greater')

print(p_value)

1.1037171700601378e-06